source 'http://rubygems.org'

gem 'nesta', :git => 'git://github.com/gma/nesta.git'
# gem 'nesta', '0.9.11'
# gem 'nesta'
gem 'rdiscount', '~> 1.6.8'
gem 'kramdown', '0.13.3'
# gem 'nesta-plugin-maldini'
gem 'nesta-plugin-maldini', :git => 'git://github.com/etc/nesta-plugin-maldini.git'
# gem (RUBY_VERSION =~ /^1.9/) ? 'ruby-debug19': 'ruby-debug'
